---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General-purpose hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key

  # Terraform-specific hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.0
    hooks:
      - id: terraform_fmt
        # Applies to all .tf files
      - id: terraform_docs
        name: Generate tf documents for modules
        files: ^modules/
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_docs
        name: Generate tf documents for root
        files: ^(main.tf|variables.tf|outputs.tf)$
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_validate
        # Runs on root-level files
        args:
          - --tf-init-args=-backend=false
      - id: terraform_tflint
        args:
          - --args=--config=/Users/tim/Documents/workspace/sre/terraform/aws/single_instance/.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--config=/Users/tim/Documents/workspace/sre/terraform/aws/single_instance/trivy.yaml
          - --args=--ignorefile=/Users/tim/Documents/workspace/sre/terraform/aws/single_instance/.trivyignore
          - --args=--exit-code=1

  # Security scanning with TFSec
  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.14
    hooks:
      - id: tfsec
        args:
          - --config-file=/Users/tim/Documents/workspace/sre/terraform/aws/single_instance/tfsec.yml
          - --soft-fail

  # Security scanning with Checkov
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.400
    hooks:
      - id: checkov
        args:
          - --soft-fail

  # Drift detection with driftctl
  - repo: local
    hooks:
      - id: driftctl-scan
        name: Check drift for dev (us-west-2)
        entry: bash -c 'cd /Users/tim/Documents/workspace/sre/terraform/aws/single_instance/environments/dev && driftctl scan --from tfstate+s3://bluedragon-tfstate-admin-dev/terraform.tfstate --filter "Type != \"aws_route_table\" && Type != \"aws_elasticache_cluster\""'
        language: system
        files: \.(tf|tfstate)$
        pass_filenames: false
        require_serial: true
        description: Runs driftctl to detect drift between Terraform state and AWS routing and elasticache
      - id: driftctl-scan-prod
        name: Check drift for prod (us-west-1)
        entry: bash -c 'cd /Users/tim/Documents/workspace/sre/terraform/aws/single_instance/environments/prod && driftctl scan --from tfstate+s3://bluedragon-tfstate-admin-prod/terraform.tfstate --filter "Type != \"aws_route_table\" && Type != \"aws_elasticache_cluster\""'
        language: system
        files: \.(tf|tfstate)$
        pass_filenames: false
        require_serial: true
        description: Runs driftctl to detect drift between Terraform state and AWS routing and elasticache
